# Generated by Django 3.1.6 on 2021-02-03 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subreddits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('upvote_ratio', models.FloatField()),
                ('score', models.IntegerField()),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('created_utc', models.DateTimeField()),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subreddits.subreddit')),
            ],
        ),
    ]
