# Generated by Django 3.1.6 on 2021-02-03 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=21)),
                ('title', models.CharField(max_length=140)),
                ('subscribers', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
